---
title: "Homework One"
output:
  html_document:
    theme: paper
    # “default”, “cerulean”, “journal”, “flatly”, “readable”, “spacelab”, “united”, “cosmo”, “lumen”, “paper”, “sandstone”, “simplex”, “yeti”
    highlight: tango # “default”, “tango”, “pygments”, “kate”, “monochrome”, “espresso”, “zenburn”, “haddock”, “textmate”
    toc: true
    toc_depth: 2
    toc_float: true
---

## Title Section

A “title” section which should at least include:

A title (e.g. Homework 1)

The authors

The date (think of using Sys.time())

## Introduction

A section called “Introduction” where you provide a short summary of the structure of your homework. Moreover, record a short video to introduce your group and include it in your R Markdown document.

## Group Members

A section called “Group Members”. This sections should have one sub-section for each group member in your team. For example, a group with three members should have three biographies in total. Each of these sub-sections (named after each group member) should include small biographies containing at least the following elements:

A picture of your choice (preferably of yourself). Make sure to include a caption for this image.

A paragraph describing your favorite hobby as well as one interesting fact about yourself.

Your favorite quote in blockquote format and be sure to reference your quote using BibTex.   

A table having two columns (first column containing the classes you are following this semester; second column containing the time of these classes).

Austin Gongora 


Ian Willick


Ciara Virgo


Mark Hancharik


## R Markdown syntax

A section called “R Markdown Syntax”, where you will demonstrate your R Markdown skills! In this section make sure to:

Show an example where the chunk option cache = T leads to a misleading answer. This example must be different from the one presented in the textbook.

Simulate 100 random samples from a standard normal distribution using the function rnorm(). Store these 100 values in a vector called x. Then, compute the empirical median, mean and variance of x. Are these results different from 0, 0 and 1 (their respective theoretical values)? Is this result surprising? Justify your answer.

Include a graph showing the histogram of x (make sure to include a caption to this figure), this can be done in R using the function hist().

Include the equation below:



Include the following in-line equation: A≡[ai,j]i,j=1,…,p

La science est le processus logique de révéler le divin
Include the following text in blue: “Vérité dans un temps, erreur dans un autre.”, Charles de Montesquieu

Include a “More info” button with hide/unhide functionality such as: More info

Include a “color box” such as the one below:

## References

A “References” section that contains all the references used in your document.
